services:
  app:
    build: /backend
    container_name: teacher-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/teacherdb
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=teacherdb
    networks:
      - app-network
    restart: always

  db:
    image: postgres:13
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=teacherdb
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: /frontend
    container_name: teacher-frontend
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

